# Experimenter Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msc-experimenter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msc-experimenter-deployment
  template:
    metadata:
      labels:
        app: msc-experimenter-deployment
    spec:
      containers:
        - name: msc-experimenter-container
          image: $$MSC_TAG_PREFIX/msc-experimenter:$$MSC_TAG_VERSION
          imagePullPolicy: $$MSC_IMAGE_PULL_POLICY
          ports:
            - containerPort: 8000
          env:
            - name: MSC_CALCULATOR_SERVICE_ADDRESS
              value: "http://calculator-service:8000"
            - name: MSC_EXPERIMENTER_SERVICE_PORT
              value: 8000

---

# Experimenter Service definition
apiVersion: v1
kind: Service
metadata:
  name: msc-experimenter
  labels:
    run: msc-experimenter
spec:
  ports:
    - name: msc-experimenter-port
      port: 8000
      targetPort: 8000
  selector:
    app: msc-experimenter-deployment
