# Reverse Proxy Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msc-reverse-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msc-reverse-proxy-deployment
  template:
    metadata:
      labels:
        app: msc-reverse-proxy-deployment
    spec:
      containers:
        - name: msc-reverse-proxy-container
          image: $$MSC_TAG_PREFIX/msc-reverse-proxy:$$MSC_TAG_VERSION
          imagePullPolicy: $$MSC_IMAGE_PULL_POLICY
          ports:
            - containerPort: 80

---

# Reverse Proxy Service definition
apiVersion: v1
kind: Service
metadata:
  name: msc-reverse-proxy
  labels:
    run: msc-reverse-proxy
spec:
  ports:
    - name: msc-reverse-proxy-port
      port: 80
      targetPort: 80
  selector:
    app: msc-reverse-proxy-deployment
  type: LoadBalancer
