# Analyzer deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msc-analyzer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msc-analyzer-deployment
  template:
    metadata:
      labels:
        app: msc-analyzer-deployment
    spec:
      containers:
        - name: msc-analyzer-container
          image: $$MSC_TAG_PREFIX/msc-analyzer:$$MSC_TAG_VERSION
          imagePullPolicy: $$MSC_IMAGE_PULL_POLICY
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              value: "$$MSC_ANALYZER_SECRET_KEY"

---

# Analyzer Service definition
apiVersion: v1
kind: Service
metadata:
  name: msc-analyzer
  labels:
    run: msc-analyzer
spec:
  ports:
    - name: msc-analyzer-port
      port: 8000
      targetPort: 8000
  selector:
    app: msc-analyzer-replicaset
